# Generated by Django 3.2.25 on 2024-08-20 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20240819_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('passenger_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='New', max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(default='Passenger', max_length=255, verbose_name='first name')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=255, null=True, verbose_name='gender')),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('passport_number', models.CharField(default='N12345678', max_length=255, unique=True)),
                ('nationality', models.CharField(default='Vietnamese', max_length=255)),
                ('passport_from_country', models.CharField(default='Vietnam', max_length=255)),
                ('due_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='account',
            name='passport_number',
        ),
        migrations.AddField(
            model_name='booking',
            name='passengers',
            field=models.ManyToManyField(related_name='flight_tickets', to='booking.Passenger'),
        ),
    ]
