# Generated by Django 3.2.25 on 2024-08-22 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20240819_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='passport_number',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Canceled', 'Canceled'), ('PendingCancellation', 'Pending Cancellation')], default='Confirmed', max_length=20),
        ),
    ]
