# Generated by Django 3.2.25 on 2024-08-22 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_account_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='account',
            name='passport_number',
        ),
    ]
