# Generated by Django 3.2.25 on 2024-08-23 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_card_card_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='multiplier',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='seat_percentage',
        ),
    ]
