# Generated by Django 3.2.25 on 2024-08-26 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20240823_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(default='New', max_length=255, validators=[django.core.validators.RegexValidator(regex='[\\u\\l]+')], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(default='User', max_length=255, validators=[django.core.validators.RegexValidator(regex='[\\u\\l]+')], verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='\\d+')]),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='\\d+')]),
        ),
        migrations.AlterField(
            model_name='card',
            name='cardholder_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(regex='[\\u\\l]+')]),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='first_name',
            field=models.CharField(default='New', max_length=255, validators=[django.core.validators.RegexValidator(regex='[\\u\\l]+')], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='last_name',
            field=models.CharField(default='Passenger', max_length=255, validators=[django.core.validators.RegexValidator(regex='[\\u\\l]+')], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='passport_number',
            field=models.CharField(default='N12345678', max_length=255, validators=[django.core.validators.RegexValidator(regex='^[\\w]+$')]),
        ),
    ]
