# Generated by Django 3.2.25 on 2024-08-26 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20240826_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(default='New', max_length=255, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]+$')], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(default='User', max_length=255, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]+$')], verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='card',
            name='cardholder_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='first_name',
            field=models.CharField(default='New', max_length=255, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]+$')], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='last_name',
            field=models.CharField(default='Passenger', max_length=255, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]+$')], verbose_name='first name'),
        ),
    ]
