# Generated by Django 3.2.25 on 2024-08-26 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20240826_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator(regex='(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$)')]),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(default='New', max_length=255, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z ]+$')], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(default='User', max_length=255, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z ]+$')], verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Member', 'Member')], max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Canceled', 'Canceled'), ('PendingCancellation', 'Pending Cancellation'), ('DeniedCancellation', 'Denied Cancellation')], default='Pending Cancellation', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='cardholder_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z ]+$')]),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='first_name',
            field=models.CharField(default='New', max_length=255, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z ]+$')], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='last_name',
            field=models.CharField(default='Passenger', max_length=255, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z ]+$')], verbose_name='first name'),
        ),
    ]
